# Default values for spring-petclinic-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Dependencies
vets-db-mysql:
  primary:
    persistence:
      enabled: false
  auth:
    database: "service_instance_db"
  image:
    tag: 8.0.25
  fullnameOverride: "vets-db-mysql"

visits-db-mysql:
  primary:
    persistence:
      enabled: false
  auth:
    database: "service_instance_db"
  image:
    tag: 8.0.25
  fullnameOverride: "visits-db-mysql"

customers-db-mysql:
  primary:
    persistence:
      enabled: false
  auth:
    database: "service_instance_db"
  image:
    tag: 8.0.25
  fullnameOverride: "customers-db-mysql"

grafana:
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  rbac:
    namespaced: true
  fullnameOverride: "grafana"
  persistence:
    enabled : false
  service:
    type: NodePort
    nodePort: 30300
  env:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: admin

prometheus:
  server:
    fullnameOverride : "prometheus-server"
    persistentVolume:
      enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false

fluent-bit:
  fullnameOverride: fluentbit
  config:
    customParsers: ""

    filters: ""

    service: |
      [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
  #      Parsers_File parsers.conf
  #      Parsers_File custom_parsers.conf
  #      HTTP_Server On
  #      HTTP_Listen 0.0.0.0
  #      HTTP_Port {{ .Values.service.port }}

    inputs: |
      [INPUT]
        Name stdin
  #      Tag spring.petclinic
  
    outputs: |
      [OUTPUT]
        Name stdout

      [OUTPUT]
        Name es
        Host http://elasticsearch.spring-petclinic.svc.cluster.local:9200
        Logstash_Format On
        Retry_Limit False

elasticsearch:
  replicas: 1
  fullnameOverride: elasticsearch
  persistence:
    enabled: false

kibana:
  fullnameOverride: kibana
  service:
    type: NodePort
    port: 5601
    nodePort: 30056
  elasticsearchHosts: http://elasticsearch.spring-petclinic.svc.cluster.local:9200

zipkin:
  fullnameOverride: zipkin
  collector:
    service:
      type: NodePort

#Values
adminServer:
  image: platform9community/admin-server
  tag: latest

apiGateway:
  image: platform9community/api-gateway
  tag: latest

visitsService:
  image: platform9community/visits-service
  tag: latest
  dbInstanceName: visits-db-mysql
  dbName: service_instance_db
  zipkinServiceName: visits-db

vetsService:
  image: platform9community/vets-service
  tag: latest
  dbInstanceName: vets-db-mysql
  dbName: service_instance_db
  zipkinServiceName: vets-db

customersService:
  image: platform9community/customers-service
  tag: latest
  dbInstanceName: customers-db-mysql
  dbName: service_instance_db
  zipkinServiceName: customers-db
